name: app_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.1.3+14

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  flutter_svg: ^2.0.14
  ionicons: ^0.2.1
  line_icons: ^2.0.3
  html_editor_enhanced: ^2.6.0
  pointer_interceptor: ^0.10.1+2
  youtube_parser: ^2.1.3
  firebase_auth: ^5.3.3
  data_table_2: ^2.5.15
  firebase_ui_firestore: ^1.7.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  image_picker: ^1.0.7
  firebase_storage: ^12.3.6
  dotted_border: ^2.1.0
  file_picker: ^8.1.4
  url_launcher: ^6.3.1
  http: ^1.2.2
  loading_animation_widget: ^1.3.0
  animated_flip_counter: ^0.3.4
  flutter_riverpod: ^2.6.1
  csv: ^6.0.0
  html_unescape: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  fl_chart: ^0.69.0
  googleapis_auth: ^1.6.0
  rounded_loading_button_plus: ^3.0.1
  logger: ^2.5.0
  image_network: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/user_avatars/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/google_fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Poppins-ExtraBold.ttf
          weight: 800




